<?php
$MESS["SBLP_Q_LA_COLUMN_NUMBER_VALUE"] = "#";
$MESS["SBLP_Q_LA_COLUMN_NAME_VALUE"] = "Artículo / Descripción";
$MESS["SBLP_Q_LA_COLUMN_QUANTITY_VALUE"] = "Cant";
$MESS["SBLP_Q_LA_COLUMN_DISCOUNT_VALUE"] = "Descuento";
$MESS["SBLP_Q_LA_COLUMN_VAT_RATE_VALUE"] = "Impuesto";
$MESS["SBLP_Q_LA_COLUMN_SUM_VALUE"] = "Total";
$MESS["SBLP_Q_LA_COLUMN_PRICE_VALUE"] = "Precio unitario";
$MESS["SBLP_Q_LA_COLUMN_MEASURE_VALUE"] = "Unidades";
